version: '3.8'

services:
    pg-database:
        image: 'postgres:16-alpine'
        container_name: 'tuzex-postgres'
        restart: always
        volumes:
            - /c/docker:/var/lib/postgresql@16/files
        ports:
            - '15432:5432'
        environment:
            POSTGRES_HOST_AUTH_METHOD: 'trust'
            command: sh -c "apk update && apk add --no-cache gzip && docker-entrypoint.sh -c 'shared_preload_libraries='cogen'' postgres -c fsync=off -c full_page_writes=off -c synchronous_commit=off -c shared_buffers=256MB -c work_mem=64MB"
    redis:
        image: 'redis:7-alpine'
        container_name: 'tuzex-redis'
        restart: always
        ports:
            - '16379:6379'
        command: redis-server --requirepass localRedisPass
