logging.level:
  org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
modules:
  customers:
    token:
      expiration: 6h
    postgres:
      url: jdbc:postgresql://localhost:15432/postgres
      username: postgres
      password: postgres
      schema: customers
    redis:
      host: localhost
      port: 16379
      password: localRedisPass
    flyway:
      enabled: true
      location: classpath:db/migration-customers
  products:
    postgres:
      url: jdbc:postgresql://localhost:15432/postgres
      username: postgres
      password: postgres
      schema: products

    flyway:
      enabled: true
      location: classpath:db/migration-products
